### ISSUE TITLE
cannot produce vue files after running 'npm run build'

### ISSUE THREAD

**Issue by syhu** [imonology/hourly#1]
steps to reproduce (on dev server):
1. get latest dev branch (commit 83850f0710299629a3347033b3f248597087206d)
2. run "npm update" (will install scalra: 2.0.0, scalra-flexform: 2.0.3)
3. run "npm run build"

expected result:
/dist directory gets created for vue processing correctly under project directory

actual result:
a build error with the following is shown:

```
Module build failed (from ../mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ../postcss-loader/src/index.js):
Error: No PostCSS Config found in: /home/imoncloud/users/imoncloud/hourly/node_modules/nprogress
    at config.search.then (/home/imoncloud/users/imoncloud/hourly/node_modules/postcss-load-config/src/index.js:
```
see screenshot too

**Comment by syhu** [comment]
the npm run build is resolved by adding a new file under project dir:

postcss.config.js

https://stackoverflow.com/questions/49709252/no-postcss-config-found

however, server still cannot start.. 

```
TypeError: Cannot set property 'sync' of null
at Object. (/home/imoncloud/users/imoncloud/hourly/node_modules/scalra-flexform/modules/flexform.js:111:52)
at Object.exports.safeCall (/home/imoncloud/users/imoncloud/hourly/node_modules/scalra/core/utility.js:210:27)
at Object. (/home/imoncloud/users/imoncloud/hourly/node_modules/scalra/core/datastore.js:667:17)
at Object.exports.safeCall (/home/imoncloud/users/imoncloud/hourly/node_modules/scalra/core/utility.js:210:27)
at /home/imoncloud/users/imoncloud/hourly/node_modules/scalra/core/datastore.js:543:11
at /home/imoncloud/users/imoncloud/hourly/node_modules/orm/lib/ChainFind.js:46:16
at Driver. (/home/imoncloud/users/imoncloud/hourly/node_modules/orm/lib/Drivers/DML/mongodb.js:154:14)
at handleCallback (/home/imoncloud/users/imoncloud/hourly/node_modules/mongodb/lib/utils.js:120:56)
at /home/imoncloud/users/imoncloud/hourly/node_modules/mongodb/lib/cursor.js:860:16
at handleCallback (/home/imoncloud/users/imoncloud/hourly/node_modules/mongodb-core/lib/cursor.js:171:5)
at setCursorNotified (/home/imoncloud/users/imoncloud/hourly/node_modules/mongodb-core/lib/cursor.js:515:3)
at /home/imoncloud/users/imoncloud/hourly/node_modules/mongodb-core/lib/cursor.js:590:16
at queryCallback (/home/imoncloud/users/imoncloud/hourly/node_modules/mongodb-core/lib/cursor.js:253:5)
at /home/imoncloud/users/imoncloud/hourly/node_modules/mongodb-core/lib/connection/pool.js:469:18
at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by syhu** [comment]
after clearing up the DB the server restarts correctly
